image: maven:3.6.0-jdk-8

stages:
  - build
  - publish

cache:
  paths:
    - .m2/repository
    - target/

before_script:
  - apt-get update && curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt install nodejs npm

build:
  stage: build
  script:
     - mvn clean install -DskipTests
  artifacts:
    paths:
    - "distribution/target/dms-distribution-0.1-bin.tar.gz"
